[package]
name = "pipeline"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "pipeline"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "tiff", "gif", "webp"] }
percent-encoding = "2"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls", "gzip", "json"] }
rphonetic = "4"
rustface = "0.1.7"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
time = { version = "0.3", features = ["formatting"] }
unicode-normalization = "0.1"

[profile.release]
opt-level = 3
